menu:
    home: /
    archive: /archives/
    about: /about/

favicon: /favicon.ico
logo: /logo.png

# 首页文章默认封面
thumbs: [/thumb/thumb-0.png,
        /thumb/thumb-1.png,
        /thumb/thumb-2.png,
        /thumb/thumb-3.png,
        /thumb/thumb-4.png,
        /thumb/thumb-5.png,
        /thumb/thumb-6.png,
        /thumb/thumb-7.png,
        /thumb/thumb-8.png,
        /thumb/thumb-9.png]

# Comment
# e.g disqus: seansun
# disqus: pupa
duoshuo: xwartz

# Analytics
# google-analytics:
ga: UA-69822347-1
# baidu-analytics:
# ba: //hm.baidu.com/hm.js?a36e15d9e2adec9a21fcdd9f686b1ed2

# Copyright Infomation
startyear: 2015
